In [1]:
import pandas as pd
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [2]:
friends_and_family = ['mom', 'dad', 'aunt', 'uncle', 'brother', 'sister', 'cousin', 'nephew', 'niece', 'daughter', 'son', 'mother', 'father', 'grandmother', 'grandfather', 'great-grandmother', 'great-grandfather', 'stepmother', 'stepfather', 'stepdaughter', 'stepson', 'stepsister', 'stepbrother', 'half-sister', 'half-brother', 'godmother', 'godfather', 'best friend', 'close friend', 'roommate', 'flatmate', 'classmate', 'colleague', 'teammate', 'neighbor', 'acquaintance', 'boyfriend', 'girlfriend', 'partner', 'fianc√©', 'spouse', 'ex-spouse']
professionals = ['boss', 'supervisor', 'manager', 'director', 'executive', 'administrator', 'employee', 'staff', 'team member', 'colleague', 'coworker', 'partner', 'client', 'customer', 'vendor', 'supplier', 'distributor', 'manufacturer', 'wholesaler', 'retailer', 'investor', 'shareholder', 'stakeholder', 'board member', 'advisor', 'consultant', 'contractor', 'freelancer', 'professional contact', 'mentor', 'coach', 'trainer', 'instructor', 'teacher', 'professor', 'scholar', 'researcher', 'scientist', 'engineer', 'programmer', 'developer', 'designer', 'analyst', 'strategist', 'planner', 'project manager', 'product manager', 'account manager', 'sales representative', 'publicist', 'marketer', 'advertiser', 'copywriter', 'journalist', 'reporter', 'editor', 'publisher', 'agent', 'lawyer', 'attorney', 'judge', 'accountant', 'auditor', 'tax specialist', 'financial advisor', 'insurance agent', 'real estate agent']
respective_individuals =['teacher', 'professor', 'instructor', 'coach', 'mentor', 'tutor', 'counselor', 'therapist', 'doctor', 'nurse', 'caregiver', 'social worker', 'minister', 'rabbi', 'imam', 'priest', 'clergy', 'therapist', 'psychiatrist', 'psychologist', 'dentist', 'optometrist', 'veterinarian', 'personal trainer', 'yoga instructor', 'pilates instructor', 'dance instructor', 'music teacher', 'art teacher', 'language tutor', 'life coach', 'career counselor', 'financial advisor', 'nutritionist', 'dietitian', 'chef']

In [3]:
combined_list = friends_and_family + professionals + respective_individuals
len(combined_list)

145

In [4]:
is_found = [0]*145

In [6]:
df = pd.read_csv('train_set.csv')
for item in combined_list:
    df[item] = 0
df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5000\1685625318.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = 0

,text,class,mom,dad,aunt,uncle,brother,sister,cousin,nephew,...,pilates instructor,dance instructor,music teacher,art teacher,language tutor,life coach,career counselor,nutritionist,dietitian,chef
0,Get two nice notebooks and write it down for e...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,I<U+0092>m sobbing reading this thread!,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Hope you have a nice day,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,My wife came in when I was around half way thr...,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,I am crying a lot of happy tears right now.,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12480,That's wild and a hell of a close call.,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12481,That's pretty much what my wife said.,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12482,I got into her line because she'd started work...,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12483,We've been friends for about a year or so.,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12484,"As for how we got together, I was taking care ...",1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
import re

sia = SentimentIntensityAnalyzer()
for index in df.index:
    if df.loc[index, 'class']==0:
        for i,item in enumerate(combined_list):
            df.loc[index, item] = 1
        continue
    scores = sia.polarity_scores(df.loc[index, 'text'])
    for i,item in enumerate(friends_and_family):
        val = 1
        if df.loc[index, 'class']==1 and scores['compound']<=0.0 and re.search(re.escape(item),  df.loc[index, 'text'], re.IGNORECASE):
            val = 0
        df.loc[index, item] = val

KeyError: 'class'

In [9]:
df

,text,class,mom,dad,aunt,uncle,brother,sister,cousin,nephew,...,pilates instructor,dance instructor,music teacher,art teacher,language tutor,life coach,career counselor,nutritionist,dietitian,chef
0,Get two nice notebooks and write it down for e...,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,I<U+0092>m sobbing reading this thread!,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,Hope you have a nice day,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,My wife came in when I was around half way thr...,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,I am crying a lot of happy tears right now.,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12480,That's wild and a hell of a close call.,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
12481,That's pretty much what my wife said.,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
12482,I got into her line because she'd started work...,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
12483,We've been friends for about a year or so.,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
12484,"As for how we got together, I was taking care ...",1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df.drop('class', axis=1)

,text,mom,dad,aunt,uncle,brother,sister,cousin,nephew,niece,...,pilates instructor,dance instructor,music teacher,art teacher,language tutor,life coach,career counselor,nutritionist,dietitian,chef
0,Get two nice notebooks and write it down for e...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,I<U+0092>m sobbing reading this thread!,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,Hope you have a nice day,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,My wife came in when I was around half way thr...,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,I am crying a lot of happy tears right now.,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12480,That's wild and a hell of a close call.,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
12481,That's pretty much what my wife said.,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
12482,I got into her line because she'd started work...,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
12483,We've been friends for about a year or so.,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
12484,"As for how we got together, I was taking care ...",1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df.to_csv('reddit_labeled.csv', index=False, escapechar='\\')

In [15]:
df = pd.read_csv('whisper_labeled.csv')
df.drop('class', axis=1)

,text,mom,dad,aunt,uncle,brother,sister,cousin,nephew,niece,...,pilates instructor,dance instructor,music teacher,art teacher,language tutor,life coach,career counselor,nutritionist,dietitian,chef
0,My mom just sold my fucking bed without tellin...,0,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,Me and this guy had a full heart to heart conv...,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,Who am I even anymore?,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,I'm a post man. N would love a lonely houswife...,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,"I've been getting butterflies when we talk, an...",1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018167,because of tumblr girls I wish I wasn't my race,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3018168,Still looking to find that first attractive gi...,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3018169,Just dropped my phone on my face three times w...,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3018170,"I never really appreciated my mom until, as a ...",0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3018171,Just found out one of my close friends liked a...,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [16]:
df.to_csv('whisper_labeled.csv', index=False, escapechar='\\')

In [20]:
df.drop(columns=df.columns[1:], inplace=True)

In [21]:
df

                                                   text
0     Barclays CEO stresses the importance of regula...
1     Barclays announces result of Rights Issue http...
2     Barclays publishes its prospectus for its √•¬£5....
3     Barclays Group Finance Director Chris Lucas is...
4     Barclays announces that Irene McDermott Brown ...
...                                                 ...
3113  Wishing you a happy and healthy Thanksgiving. ...
3114  Wouldn√å¬¢‚Ä∞√¢√Ç‚Ä∞√£¬¢t it be great if your oven recog...
3115  Yesterday, these #HealthyKids lit up Broadway ...
3116  Yo-Jelly, Danone new brand in South Africa : t...
3117  Z Bhutta: Problems with food&amp;land systems ...

[3118 rows x 1 columns]

In [31]:
for i, item in enumerate(combined_list):
    if i>=len(friends_and_family) and i < len(friends_and_family)+len(professionals):
        df[item] = 1
    else:
        df[item] = 0

In [32]:
df

,text,mom,dad,aunt,uncle,brother,sister,cousin,nephew,niece,...,pilates instructor,dance instructor,music teacher,art teacher,language tutor,life coach,career counselor,nutritionist,dietitian,chef
0,Barclays CEO stresses the importance of regula...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Barclays announces result of Rights Issue http...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Barclays publishes its prospectus for its √•¬£5....,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Barclays Group Finance Director Chris Lucas is...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Barclays announces that Irene McDermott Brown ...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3113,Wishing you a happy and healthy Thanksgiving. ...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3114,Wouldn√å¬¢‚Ä∞√¢√Ç‚Ä∞√£¬¢t it be great if your oven recog...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3115,"Yesterday, these #HealthyKids lit up Broadway ...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3116,"Yo-Jelly, Danone new brand in South Africa : t...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3117,Z Bhutta: Problems with food&amp;land systems ...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
df.to_csv('corporate_labeled.csv', index=False, escapechar='\\')